[project]
name = "Flask_aPI_Json"
description = "A simple task application, written in Flask, using Python and a json data file."
version = "0.0.1"
authors = ["Agnieszka Siwek"]
readme = "README.md"
dependencies = [
    "Flask >= 3.1.0",
    "Python >= 3.11.5"

]